version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: vue_todo_pinia
    ports:
      - '4173:4173'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
